# Generated by Django 3.2 on 2022-07-05 10:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_alter_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0d377672-d1b2-440a-b981-8c7ff57cde47'), primary_key=True, serialize=False),
        ),
    ]
