# Generated by Django 3.2 on 2022-07-05 11:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0003_auto_20220705_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('74967206-a6f9-40f7-a0f4-366e8dd9969a'), primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
