# Generated by Django 3.2 on 2022-07-05 11:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0004_auto_20220705_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='started_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='id',
            field=models.UUIDField(default=uuid.UUID('62310c15-9b22-436f-afd1-48e7820ed827'), primary_key=True, serialize=False),
        ),
    ]
