# Generated by Django 3.2 on 2022-07-05 11:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0005_auto_20220705_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cd4220ff-e87c-4bf1-bc4e-1d236e4740a4'), primary_key=True, serialize=False),
        ),
    ]
