# Generated by Django 3.2 on 2022-07-05 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0006_alter_process_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='finished_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='id',
            field=models.UUIDField(default=uuid.UUID('58788ef6-9063-44d6-8d49-216d8a5367f2'), primary_key=True, serialize=False),
        ),
    ]
