# Generated by Django 3.2 on 2022-07-22 08:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0007_auto_20220705_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='id',
            field=models.UUIDField(default=uuid.UUID('04ade24e-6380-493c-87d2-872b7d54c7bf'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('a2ef5018-223d-4ad9-9a05-8b05775e2ac9'), primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('documentType', models.TextField()),
                ('country', models.TextField()),
                ('givenNames', models.TextField()),
                ('documentNumber', models.TextField()),
                ('nationalityCode', models.TextField()),
                ('birthdate', models.TextField()),
                ('sex', models.TextField()),
                ('expiryDate', models.TextField()),
                ('personalNumber', models.TextField()),
                ('personalNumber2', models.TextField()),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticator.process')),
            ],
        ),
    ]
