# Generated by Django 3.2 on 2022-07-22 10:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0007_auto_20220705_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('face', models.ImageField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticator.process')),
            ],
        ),
    ]
