# Generated by Django 3.2 on 2022-07-22 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0008_auto_20220722_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='id',
            field=models.UUIDField(default=uuid.UUID('14fec5fb-3ecb-4db1-992f-234d9ff06b20'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='process',
            name='id',
            field=models.UUIDField(default=uuid.UUID('472b22ea-cf22-48cc-b501-729168e37560'), primary_key=True, serialize=False),
        ),
    ]
