# Generated by Django 3.2 on 2022-07-22 10:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0009_auto_20220722_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='id',
            field=models.UUIDField(default=uuid.UUID('901ca9ef-86ac-44b1-ab9c-265fd02e838a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='process',
            name='id',
            field=models.UUIDField(default=uuid.UUID('661d6a59-e9e3-45e0-bdf2-2dd87adfd75e'), primary_key=True, serialize=False),
        ),
    ]
