# Generated by Django 3.2 on 2022-07-22 12:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0010_auto_20220722_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='birthdate',
            field=models.TextField(default='1234'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='country',
            field=models.TextField(default='1234'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='documentNumber',
            field=models.TextField(default='1234'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='documentType',
            field=models.TextField(default='1234'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='expiryDate',
            field=models.TextField(default='1234'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='givenNames',
            field=models.TextField(default='1234'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0b2cbd9c-06bf-42f9-b507-cc16e350d723'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='identity',
            name='nationalityCode',
            field=models.TextField(default='1234'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='personalNumber',
            field=models.TextField(default='1234'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='personalNumber2',
            field=models.TextField(default='1234'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='sex',
            field=models.TextField(default='1234'),
        ),
        migrations.AlterField(
            model_name='process',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3b6a8633-3e07-456d-b95e-25a4cf167d88'), primary_key=True, serialize=False),
        ),
    ]
