# Generated by Django 3.2 on 2022-07-22 12:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0012_auto_20220722_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0de4019d-3e3c-4a70-aeac-828d95cb6374'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='process',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8c69bd74-e185-4e8d-82b7-e98645363857'), primary_key=True, serialize=False),
        ),
    ]
