# Generated by Django 3.2 on 2022-07-22 13:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0013_auto_20220722_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='id',
            field=models.UUIDField(default=uuid.UUID('276807ac-6653-4556-8320-9902539ec705'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='process',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c4318310-237c-409a-9f91-04b8a3cd1d57'), primary_key=True, serialize=False),
        ),
    ]
