# Generated by Django 3.2 on 2022-07-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0008_auto_20220722_1319'),
        ('authenticator', '0016_auto_20220722_1608'),
    ]

    operations = [
    ]
