# Generated by Django 3.2 on 2022-07-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0017_merge_0008_auto_20220722_1319_0016_auto_20220722_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='face',
            field=models.ImageField(upload_to='face'),
        ),
    ]
