# Generated by Django 3.2 on 2022-07-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0018_alter_face_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='bio_image',
            field=models.TextField(default='No image'),
        ),
    ]
