# Generated by Django 3.2 on 2022-07-28 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0023_alter_identity_bio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='distance',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='face',
            name='process_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='authenticator.process'),
        ),
    ]
